version: 2
jobs:
  build:
    docker:
      - image: node:16.14.0
    steps:
      - checkout
      - run:
          name: deps
          command: yarn install

      - run:
          name: build
          command: yarn build

      - persist_to_workspace:
          root: .
          paths:
            - "*"

  build_staging:
    docker:
      - image: node:16.14.0
    steps:
      - checkout
      - run:
          name: deps
          command: yarn install

      - run:
          name: build
          command: yarn build

      - persist_to_workspace:
          root: .
          paths:
            - "*"

  deploy_prod:
    docker:
      - image: node:16.14.0
    steps:
      - attach_workspace:
          at: dash
      - run:
          name: Install Firebase
          command: npm install -g firebase-tools
      - run:
          name: Deploy website
          command: firebase deploy --only hosting:prod --non-interactive

  deploy_preprod:
    docker:
      - image: node:16.14.0
    steps:
      - attach_workspace:
          at: dash
      - run:
          name: Install Firebase
          command: npm install -g firebase-tools
      - run:
          name: Deploy website to preprod
          command: firebase deploy --only hosting:preprod --non-interactive

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy_prod:
          requires:
            - build
          context: "firebase-deployments"
          filters:
            branches:
              only: main
      - build_staging:
          filters:
            branches:
              ignore: main
      - deploy_preprod:
          requires:
            - build_staging
          context: "firebase-deployments"
          filters:
            branches:
              only: development
